version: '3.7'
services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: test
    env_file:
      - .env
    command: bash -c "npm run start"
    tty: true
    ports:
      - "${PORT}:${PORT}"
    restart: always
