export enum EEnvKey {
    NODE_ENV = 'NODE_ENV',
    PORT = 'PORT',
    HOST_ADDRESS = 'HOST_ADDRESS',
    GLOBAL_PREFIX = 'GLOBAL_PREFIX',
    SWAGGER_PATH = 'SWAGGER_PATH',
    SWAGGER_IS_PUBLIC = 'SWAGGER_IS_PUBLIC',
    SWAGGER_HOST = 'SWAGGER_HOST',
    SWAGGER_VERSION = 'SWAGGER_VERSION',
    SWAGGER_TITLE = 'SWAGGER_TITLE',
    SWAGGER_DESC = 'SWAGGER_DESC',
    MONGO_URI = 'MONGO_URI',
    IS_WRITE_LOG = 'IS_WRITE_LOG',
    LOG_LEVEL = 'LOG_LEVEL',

    REDIS_HOST = 'REDIS_HOST',
    REDIS_PORT = 'REDIS_PORT',
    REDIS_PASSWORD = 'REDIS_PASSWORD',
    REDIS_DB_NUMBER = 'REDIS_DB_NUMBER',

    LIST_RPC = 'LIST_RPC',
    SAFE_BLOCK = 'SAFE_BLOCK',
    BLOCK_PER_PROCESS = 'BLOCK_PER_PROCESS',
    SLEEP_TIME = 'SLEEP_TIME',

    CONTRACT_ADDRESS = 'CONTRACT_ADDRESS',
    CONTRACT_FIRST_BLOCK = 'CONTRACT_FIRST_BLOCK',
}
